### ISSUE TITLE
tinylisp: Optional `else` on the end of `i`?

### ISSUE THREAD

**Issue by hanyuone** [dloscutoff/Esolangs#5]
In this suggestion, something like this will work:

    (d x 20)
    (i (e x 20) x)

Whereas in the current version of tinylisp, an `else` statement must be added.

**Comment by dloscutoff** [comment]
Declined. I don't think there's *that* many occasions where this would be useful; it would mostly be confusing ("wait, where's the else branch?"). Adding an explicit else branch of `()` or `nil` shouldn't be too onerous.
