### ISSUE TITLE
Regenerate: the `!` operator is undocumented

### ISSUE THREAD

**Issue by Davidebyzero** [dloscutoff/Esolangs#9]
In [Regenerate's documentation](https://github.com/dloscutoff/Esolangs/blob/master/Regenerate/README.md), `!` is only listed as a metacharacter that needs to be escaped, but isn't documented any further than that.

In its source code, it is described as [Like alternation, but stop trying other options as soon as we find one that works](https://github.com/dloscutoff/Esolangs/blob/master/Regenerate/regenerate.py#L360). But what does "one that works" mean? And what is the order of precedence when both `|` and `!` are used?

I found a way to use `!` successfully in [Print all integers](https://codegolf.stackexchange.com/a/249216/17216). But I don't quite understand exactly why it works. Why does `0|($2[0-9]!-?[1-9]())+` generate all integers, but neither `0|($2[0-9]|()-?[1-9])+` nor `0|([0-9]$2|-?[1-9]())+` nor `0|($4($3[0-9]![1-9]())!-?()){2,}` do?

**Comment by dloscutoff** [comment]
Yeah... part of the reason `!` isn't documented is that it's a bit hard to explain. Let me try with some examples. (If this goes well, I'll roll it into the documentation.)

Assume group 1 is not yet matched. Then:

- `$1` will [fail](https://ato.pxeger.com/run?1=m72qKDU9NS-1KLEkdVm0km6iUuyCpaUlaboWi1QMIQwofwGUBgA).
- `$1|x` will [match `x`](https://ato.pxeger.com/run?1=m72qKDU9NS-1KLEkdVm0km6iUuyCpaUlaboWS1QMayogTKjIAigNAA): the first alternative fails, so it tries the second one.
- `$1!x`  will also [match `x`](https://ato.pxeger.com/run?1=m72qKDU9NS-1KLEkdVm0km6iUuyCpaUlaboWS1QMFSsgTKjIAigNAA): the first alternative fails, so it tries the second one.

But `!` behaves differently from `|` when the first alternative succeeds:

- `x|y` will [match `x` and also match `y`](https://ato.pxeger.com/run?1=m72qKDU9NS-1KLEkdVm0km6iUuyCpaUlaboWiytqKiEsqMACKA0A).
- `x!y` will [match only `x`](https://ato.pxeger.com/run?1=m72qKDU9NS-1KLEkdVm0km6iUuyCpaUlaboWiysUKyEsqMACKA0A): once the first alternative succeeds, it doesn't try the second one, even if you ask for more matches.

This behavior is inspired by the "cut" from Prolog, which also uses the `!` character.

As to the parsing, `|` and `!` have the same precedence and are left-associative. So `a!b|c` parses as `a!(b|c)`, and `a|b!c` parses as `a|(b!c)`.

**Comment by Davidebyzero** [comment]
Thanks for your explanation. I just realized I made a typo in my question, though! I meant to ask the following:

`0|($2[0-9]!-?[1-9]())+` - why does this print all integers as desired,
`0|($2[0-9]!()-?[1-9])+` - but this does something different?

And why does a `!` alternative behave differently depending on whether it's zero-width or not? For example:

[`0|($2[0-9]!$3[1-9]()!-?‍()){2,}`](https://ato.pxeger.com/run?1=m72qKDU9NS-1KLEkdVm0km6iUuyCpaUlaboWNxUNajRUjKINdC1jFVWMow2BtIamoq79o4ZeDU3NaiOdWohCqPoFUBoA) - this has a zero-width joiner in it, and prints all integers
[`0|($2[0-9]!$3[1-9]()!-?()){2,}`](https://ato.pxeger.com/run?1=m72qKDU9NS-1KLEkdVm0km6iUuyCpaUlaboW-wxqNFSMog10LWMVVYyjDYG0hqairr2Gpma1kU4tRBFU7QIoDQA) - this does not, and does not

Also, `0|([0-9]$2!-?[1-9]())+` should do the same thing as `0|($2[0-9]!-?[1-9]())+` but doesn't. The entire first alternative should fail and backtrack when it hits the `$2`, even something else (the `[0-9]` in this case) "matches" successfully first. Or if there's a good reason Regenerate doesn't behave this way, why is it?

**Comment by dloscutoff** [comment]
After running through `0|($2[0-9]!-?[1-9]())+` versus `0|($2[0-9]!()-?[1-9])+`, it does look like there's a bug, probably something to do with how the match state is stored/updated. I don't know why it happens in the second case but not in the first. Will investigate further at a later time. Thanks for bringing this up.

**Comment by dloscutoff** [comment]
Bug fixed and documentation added.
